# -*- coding: utf-8 -*-
"""visualization-project-laptop-sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHJq_Th0MW6Sk_VENNrgTTpTwarZE1tI
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

file_path = '/content/Sales_data.txt'
df = pd.read_csv(file_path)
df

"""# 1"""

most_frequent_buyer = df.groupby('Contact Sex')['Profit'].sum().sort_values(ascending=False)
most_frequent_buyer

"""Based on the the grouping by gender and looking at the profit that is displayed, we can say that males are the most frequent buyers. You can see that the the total amount of profit is greater for males compared to females.

# 2
"""

df['Profit_to_Cost'] = df['Profit'] / (df['Our Cost'] + df['Shipping Cost'])
profit_to_cost = df.groupby('Contact Sex')['Profit_to_Cost'].sum()
profit_to_cost

"""If bussiness is cash constrainted then we can say that males should be targeted since the ratio of profit to 'Our Cost' and "Shipping Cost' is higher compared to females.

# 3

If consumer is cash-constrained, which gender should be targeted?
"""

df['Profit_to_Cost'] = df['Profit'] / (df['Sale Price'] + df['Shipping Cost'])
cost_to_the_customer = df.groupby('Contact Sex')['Profit_to_Cost'].sum()
cost_to_the_customer

"""If consumer is cash constrainted then Males are more likely to purchase technololgy therefore they should be targeted based on the ratio of 'Proft' to 'Sales Price' and 'Shipping Cost'

# 4
"""

age_group = df.groupby('Contact Age')['Profit'].sum().sort_values(ascending=False)
print(age_group)

age_group.plot(kind='bar')
plt.xlabel('Age')
plt.ylabel('Profit')
plt.title('Profit by Age')

"""After grouping by age, we can say that our target age to maximize profit should be 46, since the amount of purchases was higher for those who were 46 years old.

# 5
"""

product = df.groupby('Product Type')['Profit'].sum().sort_values(ascending=False)
product

"""After grouping the product types, we can see that laptops should be featured more, since more laptops are being sold compared to desktops and tablets.

# 6
"""

lead_source = df.groupby('Lead Source')['Profit'].sum().sort_values(ascending=False)
lead_source

"""The lead source that has worked in the past has been the website, since we can see that there was more profit coming in from that lead source compared to the other types.

# 7
"""

email_marketing = df[df['Lead Source'] == 'Email'].groupby('Sale Year')['Profit'].sum().sort_values(ascending=False)
email_marketing

"""The best time to do email marketing was in the year 2018, since more profit was made during that time compared to other years."""