# -*- coding: utf-8 -*-
"""stroke-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkea2SH52R6UI_ge7GWfQXq4w-J7ZTUX
"""

import numpy as np
import pandas as pd

stroke = pd.read_csv("/content/healthcare-dataset-stroke-data.csv")
stroke.head()

stroke

stroke.info()

# 1
stroke.describe()

# 2
stroke_type = stroke.select_dtypes(include='float')
stroke_type.head()

stroke_type.describe()

# 3
grouped_stroke = stroke.groupby('stroke')
grouped_stroke.head()

# 4
stroke1 = grouped_stroke.get_group(1)
stroke1.head()

# 5
stroke_float = stroke1.select_dtypes(include = 'float')
stroke_float

stroke_float.describe()

# 6
stroke_integer = stroke1.describe(include='int')
stroke_integer.describe(percentiles=[])

# 7
df = stroke.groupby(['hypertension', 'heart_disease'])
df.head()

# 8
df1 = df.get_group((1,1))
df1

# 9
df['id'].nunique()

# 10
df['stroke'].describe()[['mean', 'std']]