# -*- coding: utf-8 -*-
"""merge-join-telecom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r77YV2jlAn6ccywNRCImD5ncfkQsbTtz
"""

import pandas as pd

event = pd.read_csv('/content/event_type.csv')
log = pd.read_csv('/content/log_feature.csv')
resources = pd.read_csv('/content/resource_type.csv')
sample = pd.read_csv('/content/sample_submission.csv')
severity = pd.read_csv('/content/severity_type.csv')
test = pd.read_csv('/content/test.csv')
train = pd.read_csv('/content/train.csv')

event

log

resources

sample

severity

test

train

# 1
merge_tables = pd.merge(train, event)
merge_tables = pd.merge(merge_tables, severity)
merge_tables = pd.merge(merge_tables, resources)
merge_tables = pd.merge(merge_tables, log)
merge_tables

# 2
inner = pd.merge(train,test, on='id', how='inner')
inner

outer = pd.merge(train,test, on='id', how='outer')
outer

"""The difference bewtween inner and outer is that inner only includes values that are common in both data frmaes while outer is including everything of each data frame."""

# 3
joined = train.join(event, lsuffix='_l', rsuffix='_r')
joined

merged = pd.merge(train,event, on='id', how='left')
merged

"""the difference between join and merge is that join combines the data frame on the key col or an index, while ther merge function joins based on the data frames common column or common indice. As shown up above."""

# 4
train = train.iloc[0:10000]
event = event.iloc[10000:]
# 5
train_event = pd.concat([train, event], axis=1)
train_event

# 6
ndup = merge_tables.drop_duplicates()

ndup.reset_index(drop=True)